package: rex_socialhub
version: 1.2.2
author: Thomas Kaegi, Sascha Weidner
supportpage: github.com/phoebusryan/rex_socialhub

page:
  title: 'translate:title'
  perm: socialhub[]
  icon: rex-icon fa-share-alt
  subpages:
    hashtags:
      title: 'translate:hashtags'
      subpages:
        hashtags:
          title: 'translate:hashtags'
          perm: socialhub[hashtags]
        entries:
          title: 'translate:entries'
          perm: socialhub[entries]