package: rex_socialhub
version: 2.0.0
author: Thomas Kaegi
supportpage: github.com/phoebusryan/rex_socialhub

page:
    title: 'translate:title'
    perm: rex_socialhub[]
    icon: rex-icon fa-share-alt
    pjax: true
    subpages:
        default:
            title: 'translate:default'
            perm: rex_socialhub[default]